(function(){
'use strict';
const entry=document.getElementById('teacherEntry');if(!entry||typeof BANK==='undefined')return;
const ORIGINAL=JSON.parse(JSON.stringify(BANK));
const DRAFT_KEY='bbs1-scorm-editor-bfsdual-globalbike-lf01-v2';let current=0,authenticated=false,changed=new Set();
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const clone=o=>JSON.parse(JSON.stringify(o));
const levelName=l=>['','Orientierung','Anwendung','Transfer'][l]||l;const typeName=t=>({single:'Einfachauswahl',multi:'Mehrfachauswahl',short:'Freie Kurzantwort',match:'Zuordnung',order:'Reihenfolge',story:'Narrative Entscheidung'}[t]||t);
function mount(){
 const login=document.createElement('div');login.id='teacherLogin';login.className='teacher-login hidden';login.innerHTML=`<div class="teacher-login-card"><div class="teacher-lock">🔒</div><h2>Lehrkraftmodus</h2><p>PIN eingeben. Erst danach werden Aufgaben, Lösungen und die geschützten Transfer-Hinweise sichtbar.</p><input id="teacherPin" type="password" inputmode="numeric" maxlength="12" autocomplete="off" placeholder="PIN"><div id="teacherPinMsg" class="teacher-pin-msg"></div><div class="teacher-login-actions"><button id="teacherCancel" class="secondary">Abbrechen</button><button id="teacherOpen">Öffnen</button></div></div>`;document.body.appendChild(login);
 const overlay=document.createElement('div');overlay.id='teacherOverlay';overlay.className='teacher-overlay hidden';overlay.innerHTML=`<div class="teacher-template-shell"><header class="teacher-brand-header"><img src="assets/teacher-bbs1-aurich.svg" alt="BBS 1 Aurich"></header><main class="teacher-template-main"><section class="teacher-hero"><div class="teacher-eyebrow">Lernpfadübung · Duales System verstehen</div><h1>Lehrkraftbereich</h1><p>Aufgaben bearbeiten, Lösungen prüfen und die Paketfassung exportieren</p><div class="teacher-head-actions"><button id="teacherChangePin" class="teacher-secondary">PIN ändern</button><button id="teacherClose" class="teacher-secondary">Zur Lernpfadübung</button><button id="teacherExport" class="teacher-primary">✓ Neues SCORM speichern</button></div></section><div class="teacher-grid"><aside class="teacher-nav"><h2>Aufgaben auswählen</h2><label for="teacherSearch">Aufgabe suchen</label><input id="teacherSearch" type="search" placeholder="z. B. Aufgabe 5 oder Berufsschule"><label for="teacherJump">Aufgabe</label><select id="teacherJump"></select><details class="teacher-more"><summary>Alle Aufgaben im Überblick</summary><div class="teacher-nav-note">Orientierung und Anwendung enthalten jeweils 12 Aufgaben. Die 6 Transferkapitel bilden gemeinsam eine Entscheidungslogik.</div><div id="teacherList" class="teacher-list"></div></details></aside><div class="teacher-main"><div id="teacherStatus" class="teacher-status" role="status">Änderungen werden automatisch vorgemerkt.</div><div id="teacherEditor"></div></div></div></main></div>`;document.body.appendChild(overlay);
 entry.onclick=openLogin;$('#teacherCancel').onclick=closeLogin;$('#teacherOpen').onclick=verify;$('#teacherPin').onkeydown=e=>{if(e.key==='Enter')verify()};$('#teacherClose').onclick=closeEditor;$('#teacherExport').onclick=exportScorm;$('#teacherChangePin').onclick=changePin;$('#teacherSearch').oninput=renderList;$('#teacherJump').onchange=e=>select(+e.target.value)
}
function $(s){return document.querySelector(s)}
function openLogin(){if(authenticated)return openEditor();$('#teacherLogin').classList.remove('hidden');$('#teacherPinMsg').textContent='';setTimeout(()=>$('#teacherPin').focus(),50)}function closeLogin(){$('#teacherLogin').classList.add('hidden');$('#teacherPin').value=''}
async function hash(t){if(!crypto?.subtle)return null;const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function verify(){const input=$('#teacherPin'),msg=$('#teacherPinMsg'),until=Number(sessionStorage.getItem('bbs1-teacher-lock')||0);if(Date.now()<until){msg.textContent='Zugang nach Fehlversuchen kurz gesperrt.';return}const h=await hash(input.value.trim());if(h===TEACHER_PIN_HASH){authenticated=true;sessionStorage.removeItem('bbs1-teacher-fails');closeLogin();loadDraft();openEditor();return}let n=Number(sessionStorage.getItem('bbs1-teacher-fails')||0)+1;if(n>=5){sessionStorage.setItem('bbs1-teacher-lock',Date.now()+60000);sessionStorage.setItem('bbs1-teacher-fails','0');msg.textContent='5 falsche Eingaben. 60 Sekunden gesperrt.'}else{sessionStorage.setItem('bbs1-teacher-fails',n);msg.textContent='PIN nicht korrekt.'}input.select()}
function openEditor(){$('#teacherOverlay').classList.remove('hidden');document.body.classList.add('teacher-mode');fillJump();renderList();renderEditor()}function closeEditor(){$('#teacherOverlay').classList.add('hidden');document.body.classList.remove('teacher-mode')}
function label(i){const q=BANK[i];return `${q.type==='story'?'Transfer '+String(q.storyIndex+1).padStart(2,'0'):'Aufgabe '+String(i+1).padStart(2,'0')} · ${q.title}`}
function fillJump(){const j=$('#teacherJump');j.innerHTML=BANK.map((q,i)=>`<option value="${i}" ${i===current?'selected':''}>${E(label(i))}</option>`).join('')}
function renderList(){const raw=($('#teacherSearch').value||'').trim().toLowerCase(),qv=raw.replace(/^frage\s*/,'').replace(/^aufgabe\s*/,'').replace(/^transfer\s*/,'');const hits=BANK.map((x,i)=>({x,i})).filter(({x,i})=>!raw||[i+1,x.id,x.title,x.ask,x.scene,COMP[x.c][0],levelName(x.l),typeName(x.type),x.storyIndex!==undefined?x.storyIndex+1:''].join(' ').toLowerCase().includes(qv));$('#teacherList').innerHTML=hits.length?hits.map(({x,i})=>`<button class="teacher-list-row ${i===current?'active':''}" data-i="${i}"><span>${x.type==='story'?'T'+String(x.storyIndex+1).padStart(2,'0'):String(i+1).padStart(2,'0')}</span><b>${E(x.title)}</b><small>${E(COMP[x.c][0])} · ${E(levelName(x.l))}${changed.has(i)?' · geändert':''}</small></button>`).join(''):'<p class="teacher-empty">Keine passende Aufgabe gefunden.</p>';document.querySelectorAll('.teacher-list-row').forEach(b=>b.onclick=()=>select(+b.dataset.i))}
function select(i){if(!BANK[i])return;current=i;fillJump();renderList();renderEditor();$('.teacher-main').scrollTop=0}
function field(label,key,val,rows=2){return `<label class="teacher-field"><span>${label}</span><textarea data-key="${key}" rows="${rows}">${E(val)}</textarea></label>`}
function renderEditor(){const q=BANK[current],story=q.type==='story';$('#teacherEditor').innerHTML=`<section class="teacher-card"><div class="teacher-card-head"><div><div class="teacher-task-number">${story?`Transferkapitel ${q.storyIndex+1} von 6`:`Kernaufgabe ${current+1} von ${BANK.length}`}</div><h2>${E(q.title)}</h2></div><div class="teacher-badges"><span>${E(COMP[q.c][0])}</span><span>${E(levelName(q.l))}</span><span>${E(typeName(q.type))}</span></div></div><div class="teacher-protect"><b>Geschützt:</b> Kompetenz, Level, Aufgabentyp, 30er-Teststruktur und Moodle-Tracking können nicht versehentlich verändert werden.</div>${story?'<div class="teacher-story-note"><b>Transfer-Regel:</b> Keine Einzelantwort ist für sich „richtig“. Die technische Entscheidungslogik ist geschützt und verknüpft dieses Kapitel mit anderen Kapiteln. Mehrere Gesamtwege können vollständig tragfähig sein. Formuliere Optionen nur innerhalb der unten angezeigten Entscheidungsrolle um.</div>':''}<h3 class="teacher-section-title">1 · Situation und Auftrag</h3>${field('Kurzer Titel','title',q.title,1)}${field(story?'Situation in diesem Kapitel':'Ausgangssituation / Material','scene',q.scene,5)}${field('Frage / Arbeitsauftrag','ask',q.ask,2)}${field('Hinweis unter der Frage','criteria',q.criteria,2)}<h3 class="teacher-section-title">2 · ${story?'Entscheidungen und Folgen':'Antworten und richtige Lösung'}</h3>${answerEditor(q)}${story?logicEditor(q):''}<h3 class="teacher-section-title">3 · Rückmeldung und Hilfen</h3>${field(story?'Erklärung für die Gesamtauswertung':'Feedback / fachliche Erklärung','why',q.why,3)}${field('H1 · kurzer Impuls','hint',q.hint,2)}<details class="teacher-more"><summary>Weitere Hilfen bearbeiten</summary>${field('H2 · Lösungsweg','steps',q.steps,3)}${field('H3 · Vergleichsbeispiel','example',q.example,3)}${field('Fall-Kennzeichnung','caseLabel',q.caseLabel,2)}</details><div id="teacherValidation" class="teacher-validation"></div><div class="teacher-bottom-actions"><button id="teacherPrev" class="teacher-secondary" ${current===0?'disabled':''}>← vorherige</button><button id="teacherReset" class="teacher-reset">Diese Aufgabe zurücksetzen</button><button id="teacherNext" class="teacher-secondary" ${current===BANK.length-1?'disabled':''}>nächste →</button></div></section>`;bindCommon(q);bindAnswers(q);validateCurrent();$('#teacherPrev').onclick=()=>current>0&&select(current-1);$('#teacherNext').onclick=()=>current<BANK.length-1&&select(current+1);$('#teacherReset').onclick=()=>{if(!confirm('Diese Aufgabe wirklich zurücksetzen?'))return;BANK[current]=clone(ORIGINAL[current]);changed.delete(current);saveDraft();renderList();renderEditor();status('Aufgabe zurückgesetzt.','ok')}}
function answerEditor(q){
 if(q.type==='story')return `<div class="teacher-answerbox"><p>Formuliere drei echte Entscheidungsalternativen. <b>Keine wird isoliert als richtig markiert.</b> Die graue Entscheidungsrolle ist technisch geschützt und darf inhaltlich nicht verändert werden.</p>${q.options.map((o,i)=>`<div class="teacher-option-role">Rolle ${String.fromCharCode(65+i)} · ${E(q.logicRoles?.[i]||'geschützte Logikrolle')}</div><div class="teacher-option"><span>${String.fromCharCode(65+i)}</span><textarea class="teacher-option-text" data-i="${i}" rows="2">${E(o)}</textarea></div><label class="teacher-consequence"><span>Folge ${String.fromCharCode(65+i)}</span><textarea class="teacher-consequence-text" data-i="${i}" rows="2">${E(q.consequences[i])}</textarea></label>`).join('')}</div>`;
 if(q.type==='single'||q.type==='multi')return `<div class="teacher-answerbox"><p>${q.type==='single'?'Markiere genau eine richtige Antwort.':'Markiere alle richtigen Antworten.'}</p>${q.options.map((o,i)=>`<label class="teacher-option"><input class="teacher-correct" type="${q.type==='single'?'radio':'checkbox'}" name="correct" data-i="${i}" ${(q.type==='single'?q.answer===i:q.answer.includes(i))?'checked':''}><span>${String.fromCharCode(65+i)}</span><textarea class="teacher-option-text" data-i="${i}" rows="2">${E(o)}</textarea><em>richtig</em></label>`).join('')}</div>`;
 if(q.type==='short')return `<div class="teacher-answerbox"><p>Alle Schreibweisen gelten als richtig.</p>${q.answer.map((a,i)=>`<div class="teacher-short-row"><span>${i+1}.</span><input class="teacher-short" data-i="${i}" value="${E(a)}"><button class="teacher-remove-short" data-i="${i}" ${q.answer.length===1?'disabled':''}>×</button></div>`).join('')}<button id="addShort" class="teacher-secondary">+ weitere richtige Schreibweise</button></div>`;
 if(q.type==='match')return `<div class="teacher-answerbox"><div class="teacher-match-categories"><b>Kategorien</b>${q.options[1].map((x,i)=>`<label><span>${i+1}</span><input class="teacher-match-cat" data-i="${i}" value="${E(x)}"></label>`).join('')}</div>${q.options[0].map((x,i)=>`<div class="teacher-match-row"><label><span>Aussage ${i+1}</span><textarea class="teacher-match-item" data-i="${i}" rows="2">${E(x)}</textarea></label><label><span>richtige Kategorie</span><select class="teacher-match-answer" data-i="${i}">${q.options[1].map((c,k)=>`<option value="${k}" ${q.answer[i]===k?'selected':''}>${E(c)}</option>`).join('')}</select></label></div>`).join('')}</div>`;
 if(q.type==='order')return `<div class="teacher-answerbox"><div class="teacher-order-options">${q.options.map((x,i)=>`<label><span>Schritt ${i+1}</span><input class="teacher-order-text" data-i="${i}" value="${E(x)}"></label>`).join('')}</div><div class="teacher-order-solution"><b>Richtige Reihenfolge</b>${q.answer.map((a,pos)=>`<label><span>Position ${pos+1}</span><select class="teacher-order-answer" data-pos="${pos}">${q.options.map((x,i)=>`<option value="${i}" ${a===i?'selected':''}>${E(x)}</option>`).join('')}</select></label>`).join('')}</div></div>`;return ''
}
function logicEditor(q){const linked=TRANSFER_RULES.filter(r=>r.steps.includes(q.storyIndex));return `<div class="teacher-answerbox teacher-logicbox"><p><b>Entscheidungsnetz geschützt.</b> Dieses Kapitel wird mit ${linked.length} anderen Logikbeziehungen ausgewertet. Die Verknüpfungen selbst sind absichtlich nicht editierbar, damit das SCORM nicht versehentlich fachlich oder technisch beschädigt wird.</p><ul>${linked.map(r=>`<li>${E(r.label)}</li>`).join('')}</ul></div>`}
function bindCommon(q){document.querySelectorAll('#teacherEditor [data-key]').forEach(el=>el.oninput=()=>{q[el.dataset.key]=el.value;mark()})}
function bindAnswers(q){
 document.querySelectorAll('.teacher-option-text').forEach(el=>el.oninput=()=>{q.options[+el.dataset.i]=el.value;mark()});
 if(q.type==='story'){document.querySelectorAll('.teacher-consequence-text').forEach(el=>el.oninput=()=>{q.consequences[+el.dataset.i]=el.value;mark()});return}
 if(q.type==='single'||q.type==='multi')document.querySelectorAll('.teacher-correct').forEach(el=>el.onchange=()=>{q.answer=q.type==='single'?+el.dataset.i:[...document.querySelectorAll('.teacher-correct:checked')].map(x=>+x.dataset.i).sort((a,b)=>a-b);mark()});
 else if(q.type==='short'){document.querySelectorAll('.teacher-short').forEach(el=>el.oninput=()=>{q.answer[+el.dataset.i]=el.value;mark()});document.querySelectorAll('.teacher-remove-short').forEach(b=>b.onclick=e=>{e.preventDefault();if(q.answer.length<=1)return;q.answer.splice(+b.dataset.i,1);mark();renderEditor()});$('#addShort').onclick=e=>{e.preventDefault();q.answer.push('');mark();renderEditor()}}
 else if(q.type==='match'){document.querySelectorAll('.teacher-match-cat').forEach(el=>el.onchange=()=>{q.options[1][+el.dataset.i]=el.value.trim();mark();renderEditor()});document.querySelectorAll('.teacher-match-item').forEach(el=>el.oninput=()=>{q.options[0][+el.dataset.i]=el.value;mark()});document.querySelectorAll('.teacher-match-answer').forEach(el=>el.onchange=()=>{q.answer[+el.dataset.i]=+el.value;mark()})}
 else if(q.type==='order'){document.querySelectorAll('.teacher-order-text').forEach(el=>el.onchange=()=>{q.options[+el.dataset.i]=el.value.trim();mark();renderEditor()});document.querySelectorAll('.teacher-order-answer').forEach(el=>el.onchange=()=>{q.answer[+el.dataset.pos]=+el.value;mark()})}
}
function mark(){changed.add(current);saveDraft();renderList();validateCurrent();status('Änderung automatisch vorgemerkt.','ok')}
function unique(a){return new Set(a.map(x=>String(x).trim().toLowerCase())).size===a.length}
function lengthTrap(options){if(!options||options.length<3)return false;const l=options.map(x=>String(x).trim().length),mx=Math.max(...l),mn=Math.min(...l),avg=l.reduce((a,b)=>a+b,0)/l.length;return mx-mn>Math.max(40,avg*.7)}
function validate(q){const e=[],req=['title','scene','ask','criteria','why','hint','steps','example','caseLabel'];for(const k of req)if(!String(q[k]||'').trim())e.push(`${k} fehlt`);
 if(q.type==='story'){if(!Array.isArray(q.options)||q.options.length!==3||q.options.some(x=>!String(x).trim()))e.push('Es werden genau drei ausgefüllte Entscheidungsalternativen benötigt');else if(!unique(q.options))e.push('Entscheidungsalternativen dürfen nicht doppelt sein');if(!Array.isArray(q.consequences)||q.consequences.length!==3||q.consequences.some(x=>!String(x).trim()))e.push('Zu jeder Entscheidung muss eine Folge formuliert sein');if(!Array.isArray(q.logicRoles)||q.logicRoles.length!==3)e.push('Geschützte Entscheidungsrollen fehlen');if(lengthTrap(q.options))e.push('Antwortlängen sind stark unterschiedlich – eine Option könnte auffallen')}
 else if(q.type==='single'||q.type==='multi'){if(q.options.some(x=>!String(x).trim()))e.push('Ein Antworttext ist leer');if(!unique(q.options))e.push('Antworttexte dürfen nicht doppelt sein');if(lengthTrap(q.options))e.push('Antwortlängen sind stark unterschiedlich – Lösung könnte erkennbar sein');if(q.type==='single'&&(!Number.isInteger(q.answer)||q.answer<0||q.answer>=q.options.length))e.push('Richtige Antwort fehlt');if(q.type==='multi'&&(!Array.isArray(q.answer)||!q.answer.length))e.push('Richtige Mehrfachauswahl fehlt')}
 else if(q.type==='short'){if(!q.answer?.length||q.answer.some(x=>!String(x).trim()))e.push('Mindestens eine richtige Kurzantwort fehlt')}
 else if(q.type==='match'){if(q.options?.[0]?.some(x=>!String(x).trim())||q.options?.[1]?.some(x=>!String(x).trim()))e.push('Aussage oder Kategorie ist leer');if(!Array.isArray(q.answer)||q.answer.length!==q.options[0].length)e.push('Zuordnung ist unvollständig')}
 else if(q.type==='order'){if(q.options.some(x=>!String(x).trim())||new Set(q.answer).size!==q.options.length)e.push('Reihenfolge ist unvollständig')}
 return e}
function globalValidate(){const e=[];const req={'1':12,'2':12,'3':6};for(const l of [1,2,3]){const ids=CORE_PLAN[String(l)]||[];if(ids.length!==req[String(l)])e.push(`${levelName(l)} benötigt in dieser Testfassung genau ${req[String(l)]} Aufgaben`)}for(const l of [1,2]){const ids=CORE_PLAN[String(l)]||[];for(let c=0;c<5;c++){const n=ids.filter(id=>BANK[id]?.c===c).length;if(n<2)e.push(`${levelName(l)} benötigt mindestens zwei Aufgaben für ${COMP[c][0]}`)}}for(let c=0;c<5;c++){const n=(CORE_PLAN['3']||[]).filter(id=>BANK[id]?.c===c).length;if(n<1)e.push(`Transfer benötigt mindestens eine Entscheidung für ${COMP[c][0]}`)}const storyIds=CORE_PLAN['3'];if(storyIds.some(id=>BANK[id]?.type!=='story'))e.push('Transfer-Testaufgaben müssen narrative Entscheidungen sein');if(!Array.isArray(TRANSFER_RULES)||TRANSFER_RULES.length<4)e.push('Das Transfer-Entscheidungsnetz ist unvollständig');const covered=new Set();for(const r of TRANSFER_RULES){if(!Array.isArray(r.steps)||r.steps.length<2)e.push(`Transferregel ${r.label||r.id} ist unvollständig`);(r.steps||[]).forEach(i=>covered.add(i))}for(let i=0;i<6;i++)if(!covered.has(i))e.push(`Transferkapitel ${i+1} ist nicht mit dem Entscheidungsnetz verknüpft`);return e}
function validateCurrent(){const errors=validate(BANK[current]),el=$('#teacherValidation');if(!el)return;el.className='teacher-validation '+(errors.length?'bad':'good');el.textContent=errors.length?errors.join(' · '):'Aufgabe vollständig. Die Gesamtstruktur wird beim Export zusätzlich geprüft.';}
function validateAll(){const task=BANK.flatMap((q,i)=>validate(q).map(msg=>({i,msg}))),global=globalValidate().map(msg=>({i:0,msg}));return task.concat(global)}
function status(text,kind=''){const el=$('#teacherStatus');if(el){el.textContent=text;el.className='teacher-status '+kind}}
function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify({bank:BANK,pin:TEACHER_PIN_HASH,changed:[...changed],at:Date.now()}))}catch(e){}}
function loadDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(d?.bank?.length===BANK.length){BANK.splice(0,BANK.length,...clone(d.bank));if(d.pin)TEACHER_PIN_HASH=d.pin;changed=new Set(d.changed||[])}}catch(e){}}
function buildData(){return 'const COMP='+JSON.stringify(COMP)+';\nconst BANK='+JSON.stringify(BANK)+';\nconst CORE_PLAN='+JSON.stringify(CORE_PLAN)+';\nconst TRANSFER_RULES='+JSON.stringify(TRANSFER_RULES)+';\n'}
async function exportScorm(){const errors=validateAll();if(errors.length){select(errors[0].i);status(`Export gestoppt: ${errors[0].msg}`,'bad');return}if(typeof JSZip==='undefined'){status('ZIP-Modul fehlt.','bad');return}const btn=$('#teacherExport');btn.disabled=true;btn.textContent='SCORM wird erstellt …';status('Alle Aufgaben, Quoten und das geschützte Entscheidungsnetz werden geprüft.','ok');try{const zip=new JSZip(),files=['index.html','style.css','teacher-template.css','engine.js','progress.js','app.js','teacher.js','jszip.min.js','assets/global-bike.svg','assets/bbs.svg','assets/teacher-bbs1-aurich.svg','LEHRKRAFT-HINWEISE.html','TESTPROTOKOLL.txt','imsmanifest.xml'];for(const path of files){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path);zip.file(path,await r.arrayBuffer())}zip.file('data.js',buildData());zip.file('teacher-config.js',`let TEACHER_PIN_HASH='${TEACHER_PIN_HASH}';\n`);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='01_Duales_System_verstehen_bearbeitet.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);status('✓ Neues SCORM gespeichert. In Moodle nur die Paketdatei ersetzen.','ok')}catch(e){console.error(e);status('Export fehlgeschlagen.','bad')}finally{btn.disabled=false;btn.textContent='✓ Neues SCORM speichern'}}
async function changePin(){const a=prompt('Neue PIN eingeben (4–12 Ziffern):');if(a===null)return;if(!/^\d{4,12}$/.test(a))return status('Bitte 4–12 Ziffern verwenden.','bad');const b=prompt('Neue PIN erneut eingeben:');if(a!==b)return status('PINs stimmen nicht überein.','bad');TEACHER_PIN_HASH=await hash(a);saveDraft();status('✓ Neue PIN gilt im neu exportierten SCORM.','ok')}
mount();
})();
